import {
  AlgoliaOriginal,
  AmazonwebservicesOriginalWordmark,
  AngularOriginal,
  AnsibleOriginalWordmark,
  ApachekafkaOriginalWordmark,
  ArgocdOriginal,
  OauthOriginal,
  AzureOriginalWordmark,
  BashOriginal,
  BitbucketOriginalWordmark,
  BootstrapOriginalWordmark,
  CassandraOriginalWordmark,
  ClojureOriginal,
  CloudflareOriginalWordmark,
  COriginal,
  CouchdbOriginalWordmark,
  CplusplusOriginal,
  CsharpOriginal,
  DartOriginal,
  DigitaloceanOriginalWordmark,
  DjangoPlainWordmark,
  DockerOriginalWordmark,
  ElasticsearchOriginalWordmark,
  ElixirOriginal,
  EmberOriginalWordmark,
  ErlangOriginal,
  ExpressOriginalWordmark,
  FlaskOriginalWordmark,
  FsharpOriginal,
  GatsbyOriginalWordmark,
  GithubOriginalWordmark,
  GitlabOriginalWordmark,
  GooglecloudOriginalWordmark,
  GoOriginalWordmark,
  GrafanaOriginalWordmark,
  GroovyOriginal,
  HaskellOriginal,
  HelmOriginal,
  HerokuOriginalWordmark,
  InfluxdbOriginalWordmark,
  JavaOriginalWordmark,
  JavascriptOriginal,
  JenkinsOriginal,
  KotlinOriginal,
  KubernetesOriginalWordmark,
  LaravelOriginalWordmark,
  LuaOriginal,
  MariadbOriginalWordmark,
  MatlabOriginal,
  MicrosoftsqlserverPlainWordmark,
  MongodbOriginalWordmark,
  MysqlOriginalWordmark,
  Neo4jOriginalWordmark,
  NestjsOriginal,
  NetlifyOriginalWordmark,
  NextjsOriginalWordmark,
  NimOriginal,
  NuxtjsOriginalWordmark,
  OktaOriginal,
  OpentelemetryOriginal,
  PerlOriginal,
  PhpOriginal,
  PostgresqlOriginalWordmark,
  PowershellOriginal,
  PrometheusOriginal,
  PythonOriginalWordmark,
  RabbitmqOriginalWordmark,
  RailsOriginalWordmark,
  ReactOriginalWordmark,
  RedisOriginalWordmark,
  ROriginal,
  RubyOriginalWordmark,
  RustOriginal,
  ScalaOriginalWordmark,
  SplunkOriginalWordmark,
  SpringOriginalWordmark,
  SqliteOriginalWordmark,
  SvelteOriginal,
  SwiftOriginal,
  SymfonyOriginalWordmark,
  TailwindcssOriginalWordmark,
  TerraformOriginalWordmark,
  TypescriptOriginal,
  VaultOriginal,
  VercelOriginalWordmark,
  VisualstudioPlain,
  VuejsOriginalWordmark,
} from "devicons-react";

import {
  Cloud,
  Computer,
  Dns,
  Folder,
  PhoneIphone,
  Router,
  Security,
  Storage,
  SwapHoriz,
  VpnLock,
} from "@mui/icons-material";

interface IconProps {
  size?: number;
  style?: React.CSSProperties;
}

export const iconMap: Record<string, React.ComponentType<IconProps>> = {
  java: JavaOriginalWordmark,
  javascript: JavascriptOriginal,
  typescript: TypescriptOriginal,
  python: PythonOriginalWordmark,
  ruby: RubyOriginalWordmark,
  php: PhpOriginal,
  c: COriginal,
  cpp: CplusplusOriginal,
  csharp: CsharpOriginal,
  go: GoOriginalWordmark,
  kotlin: KotlinOriginal,
  swift: SwiftOriginal,
  dart: DartOriginal,
  rust: RustOriginal,
  scala: ScalaOriginalWordmark,
  perl: PerlOriginal,
  haskell: HaskellOriginal,
  elixir: ElixirOriginal,
  clojure: ClojureOriginal,
  erlang: ErlangOriginal,
  shell: BashOriginal,
  powershell: PowershellOriginal,
  r: ROriginal,
  matlab: MatlabOriginal,
  fsharp: FsharpOriginal,
  visualbasic: VisualstudioPlain,
  lua: LuaOriginal,
  groovy: GroovyOriginal,
  nim: NimOriginal,
  postgresql: PostgresqlOriginalWordmark,
  mysql: MysqlOriginalWordmark,
  mariadb: MariadbOriginalWordmark,
  mongodb: MongodbOriginalWordmark,
  redis: RedisOriginalWordmark,
  cassandra: CassandraOriginalWordmark,
  sqlserver: MicrosoftsqlserverPlainWordmark,
  sqlite: SqliteOriginalWordmark,
  elasticsearch: ElasticsearchOriginalWordmark,
  neo4j: Neo4jOriginalWordmark,
  couchdb: CouchdbOriginalWordmark,
  influxdb: InfluxdbOriginalWordmark,
  docker: DockerOriginalWordmark,
  kubernetes: KubernetesOriginalWordmark,
  terraform: TerraformOriginalWordmark,
  ansible: AnsibleOriginalWordmark,
  jenkins: JenkinsOriginal,
  github: GithubOriginalWordmark,
  gitlab: GitlabOriginalWordmark,
  bitbucket: BitbucketOriginalWordmark,
  argo: ArgocdOriginal,
  helm: HelmOriginal,
  react: ReactOriginalWordmark,
  angular: AngularOriginal,
  vue: VuejsOriginalWordmark,
  nextjs: NextjsOriginalWordmark,
  nuxtjs: NuxtjsOriginalWordmark,
  svelte: SvelteOriginal,
  nestjs: NestjsOriginal,
  django: DjangoPlainWordmark,
  rails: RailsOriginalWordmark,
  spring: SpringOriginalWordmark,
  flask: FlaskOriginalWordmark,
  express: ExpressOriginalWordmark,
  laravel: LaravelOriginalWordmark,
  symfony: SymfonyOriginalWordmark,
  bootstrap: BootstrapOriginalWordmark,
  tailwind: TailwindcssOriginalWordmark,
  gatsby: GatsbyOriginalWordmark,
  ember: EmberOriginalWordmark,
  kafka: ApachekafkaOriginalWordmark,
  rabbitmq: RabbitmqOriginalWordmark,
  prometheus: PrometheusOriginal,
  grafana: GrafanaOriginalWordmark,
  splunk: SplunkOriginalWordmark,
  opentelemetry: OpentelemetryOriginal,
  auth0: OauthOriginal,
  algolia: AlgoliaOriginal,
  cloudflare: CloudflareOriginalWordmark,
  vault: VaultOriginal,
  okta: OktaOriginal,
  aws: AmazonwebservicesOriginalWordmark,
  azure: AzureOriginalWordmark,
  gcp: GooglecloudOriginalWordmark,
  digitalocean: DigitaloceanOriginalWordmark,
  heroku: HerokuOriginalWordmark,
  vercel: VercelOriginalWordmark,
  netlify: NetlifyOriginalWordmark,
  server: Storage,
  "database-server": Dns,
  "client-device": Computer,
  "mobile-device": PhoneIphone,
  router: Router,
  firewall: Security,
  cloud: Cloud,
  vpn: VpnLock,
  storage: Folder,
  "load-balancer": SwapHoriz,
  default: Storage,
};

export const getIconComponent = (
  iconName: string
): React.ComponentType<IconProps> => {
  return iconMap[iconName] || iconMap.default;
};
