import {
  AlgoliaOriginal,
  AmazonwebservicesOriginalWordmark,
  AngularOriginal,
  AnsibleOriginal,
  ApachekafkaOriginal,
  ArgocdOriginal,
  AzureOriginal,
  BashOriginal,
  BitbucketOriginal,
  BootstrapOriginal,
  CassandraOriginal,
  ClojureOriginal,
  CloudflareOriginal,
  COriginal,
  CouchdbOriginal,
  CplusplusOriginal,
  CsharpOriginal,
  DartOriginal,
  DigitaloceanOriginal,
  DjangoPlain,
  DockerOriginal,
  ElasticsearchOriginal,
  ElixirOriginal,
  EmberOriginal,
  ErlangOriginal,
  ExpressOriginal,
  FlaskOriginal,
  FsharpOriginal,
  GatsbyOriginal,
  GithubOriginal,
  GitlabOriginal,
  GooglecloudOriginal,
  GoOriginal,
  GrafanaOriginal,
  GroovyOriginal,
  GrpcOriginal,
  HaskellOriginal,
  HelmOriginal,
  HerokuOriginal,
  InfluxdbOriginal,
  JavaOriginal,
  JavascriptOriginal,
  JenkinsOriginal,
  KotlinOriginal,
  KubernetesOriginal,
  LaravelOriginal,
  LuaOriginal,
  MariadbOriginal,
  MatlabOriginal,
  MicrosoftsqlserverPlain,
  MongodbOriginal,
  MysqlOriginal,
  Neo4jOriginal,
  NestjsOriginal,
  NetlifyOriginal,
  NextjsOriginal,
  NimOriginal,
  NuxtjsOriginal,
  OauthOriginal,
  OktaOriginal,
  OpentelemetryOriginal,
  PerlOriginal,
  PhpOriginal,
  PostgresqlOriginal,
  PowershellOriginal,
  PrometheusOriginal,
  PythonOriginal,
  RabbitmqOriginal,
  RailsOriginalWordmark,
  ReactOriginal,
  RedisOriginal,
  ROriginal,
  RubyOriginal,
  RustOriginal,
  ScalaOriginal,
  SplunkOriginalWordmark,
  SpringOriginal,
  SqliteOriginal,
  SvelteOriginal,
  SwiftOriginal,
  SymfonyOriginal,
  TailwindcssOriginal,
  TerraformOriginal,
  TypescriptOriginal,
  VaultOriginal,
  VercelOriginal,
  VisualstudioPlain,
  VuejsOriginal,
} from "devicons-react";

import {
  Cloud,
  CloudUpload,
  Computer,
  DeviceHub,
  Dns,
  Folder,
  Http,
  Https,
  ImportExport,
  PhoneIphone,
  Router,
  Security,
  Storage,
  SwapHoriz,
  VpnLock,
  Person,
} from "@mui/icons-material";

interface IconProps {
  size?: number;
  style?: React.CSSProperties;
}

export const iconMap: Record<string, React.ComponentType<IconProps>> = {
  java: JavaOriginal,
  javascript: JavascriptOriginal,
  typescript: TypescriptOriginal,
  python: PythonOriginal,
  ruby: RubyOriginal,
  php: PhpOriginal,
  c: COriginal,
  cpp: CplusplusOriginal,
  csharp: CsharpOriginal,
  go: GoOriginal,
  kotlin: KotlinOriginal,
  swift: SwiftOriginal,
  dart: DartOriginal,
  rust: RustOriginal,
  scala: ScalaOriginal,
  perl: PerlOriginal,
  haskell: HaskellOriginal,
  elixir: ElixirOriginal,
  clojure: ClojureOriginal,
  erlang: ErlangOriginal,
  shell: BashOriginal,
  powershell: PowershellOriginal,
  r: ROriginal,
  matlab: MatlabOriginal,
  fsharp: FsharpOriginal,
  visualbasic: VisualstudioPlain,
  lua: LuaOriginal,
  groovy: GroovyOriginal,
  nim: NimOriginal,
  postgresql: PostgresqlOriginal,
  mysql: MysqlOriginal,
  mariadb: MariadbOriginal,
  mongodb: MongodbOriginal,
  redis: RedisOriginal,
  cassandra: CassandraOriginal,
  sqlserver: MicrosoftsqlserverPlain,
  sqlite: SqliteOriginal,
  elasticsearch: ElasticsearchOriginal,
  neo4j: Neo4jOriginal,
  couchdb: CouchdbOriginal,
  influxdb: InfluxdbOriginal,
  docker: DockerOriginal,
  kubernetes: KubernetesOriginal,
  terraform: TerraformOriginal,
  ansible: AnsibleOriginal,
  jenkins: JenkinsOriginal,
  github: GithubOriginal,
  gitlab: GitlabOriginal,
  bitbucket: BitbucketOriginal,
  argo: ArgocdOriginal,
  helm: HelmOriginal,
  react: ReactOriginal,
  angular: AngularOriginal,
  vue: VuejsOriginal,
  nextjs: NextjsOriginal,
  nuxtjs: NuxtjsOriginal,
  svelte: SvelteOriginal,
  nestjs: NestjsOriginal,
  django: DjangoPlain,
  rails: RailsOriginalWordmark,
  spring: SpringOriginal,
  flask: FlaskOriginal,
  express: ExpressOriginal,
  laravel: LaravelOriginal,
  symfony: SymfonyOriginal,
  bootstrap: BootstrapOriginal,
  tailwind: TailwindcssOriginal,
  gatsby: GatsbyOriginal,
  ember: EmberOriginal,
  kafka: ApachekafkaOriginal,
  rabbitmq: RabbitmqOriginal,
  prometheus: PrometheusOriginal,
  grafana: GrafanaOriginal,
  splunk: SplunkOriginalWordmark,
  opentelemetry: OpentelemetryOriginal,
  auth0: OauthOriginal,
  algolia: AlgoliaOriginal,
  cloudflare: CloudflareOriginal,
  vault: VaultOriginal,
  okta: OktaOriginal,
  aws: AmazonwebservicesOriginalWordmark,
  azure: AzureOriginal,
  gcp: GooglecloudOriginal,
  digitalocean: DigitaloceanOriginal,
  heroku: HerokuOriginal,
  vercel: VercelOriginal,
  netlify: NetlifyOriginal,
  server: Storage,
  "database-server": Dns,
  "client-device": Computer,
  "mobile-device": PhoneIphone,
  router: Router,
  firewall: Security,
  cloud: Cloud,
  vpn: VpnLock,
  storage: Folder,
  "load-balancer": SwapHoriz,
  http: Http,
  https: Https,
  tcp: DeviceHub,
  udp: DeviceHub,
  websocket: ImportExport,
  grpc: GrpcOriginal,
  mqtt: DeviceHub,
  amqp: DeviceHub,
  ftp: CloudUpload,
  sftp: CloudUpload,
  ssh: Security,
  users: Person,
  dns: Dns,
  default: Storage,
};

export const getIconComponent = (
  iconName: string
): React.ComponentType<IconProps> => {
  return iconMap[iconName] || iconMap.default;
};
