name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: "cypress-${{ github.ref }}"
  cancel-in-progress: true

env:
  VITE_STORAGE_ACTIVE: true
  VITE_PLUGINS: "@archivisio/defaul,@archivisio/cross-level-connections,@archivisio/simon-brown-credit"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install server
        run: npm install -g serve

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: serve -l 5173 -s dist
          command: npm run test:ci
          wait-on: 'http://localhost:5173'
          browser: chrome
          record: false

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
