name: Push Docker image

on:
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: "docker-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.public
          push: true
          tags: |
            eth3rnit3/c4_modelizer:${{ github.event.release.tag_name }}
            eth3rnit3/c4_modelizer:latest